# main.yml
# GitHub Actions workflow to build and deploy the React application to GitHub Pages

name: Build and Deploy React App

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job builds the application
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sets up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Use a current LTS version of Node.js
          cache: 'npm' # Caches npm dependencies for faster builds

      # 3. Installs project dependencies
      - name: Install dependencies
        run: npm ci # 'ci' is faster and safer for continuous integration environments

      # 4. Builds the application for production
      - name: Build application
        run: npm run build # Assumes your package.json has a "build" script

      # 5. Uploads the build artifact to be used by the deployment job
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # The path to the folder to upload
          path: './dist' # <-- Change to 'dist' # <-- IMPORTANT: Change to './dist' if you are using Vite

  # This job deploys the application
  deploy:
    # Requires the 'build' job to complete successfully before running
    needs: build

    # Grant permissions for the workflow to deploy to GitHub Pages
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment token

    # Specify the deployment environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      # Deploys the uploaded artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
